// cifa-desktop/src/components/Sidebar.tsx
// src/components/Sidebar.tsx

'use client';

import Link from 'next/link';
import { usePathname } from 'next/navigation';

const Icon = ({ path }: { path: string }) => (
  <svg className="w-5 h-5 flex-shrink-0" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
    <path d={path} strokeLinecap="round" strokeLinejoin="round" />
  </svg>
);

const navItems = [
  { name: 'Dashboard', href: '/dashboard', iconPath: 'M3 3h7v7H3zm11 0h7v7h-7zm0 11h7v7h-7zm-11 0h7v7H3z' },
  { name: 'Estudantes', href: '/estudantes', iconPath: 'M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2 M12 7a4 4 0 1 0-8 0 4 4 0 0 0 8 0z M23 21v-2a4 4 0 0 0-3-3.87 M16 3.13a4 4 0 0 1 0 7.75' },
  { name: 'Relatórios', href: '/logs', iconPath: 'M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z M14 2v6h6' },
];

export default function Sidebar() {
  const pathname = usePathname();

  return (
    <aside className="w-[280px] bg-indigo-950 flex flex-col justify-between p-8 flex-shrink-0 h-full border-r border-white/5">
      <div>
        <div className="flex items-center gap-3 mb-10">
          <div className="text-white font-bold text-2xl tracking-wide">CIFA</div>
          <p className="text-indigo-200 text-[10px] leading-tight font-poppins">
            Controle Inteligente <br /> de Fluxo Acadêmico
          </p>
        </div>

        <nav className="flex flex-col gap-2">
          {navItems.map((item) => {
            const isActive = pathname.startsWith(item.href);
            return (
              <Link
                key={item.name}
                href={item.href}
                className={`flex items-center gap-4 px-5 py-3.5 rounded-xl text-base font-medium transition-all duration-200 ${
                  isActive
                    ? 'bg-white text-indigo-950 shadow-lg scale-[1.02]'
                    : 'text-white hover:bg-indigo-900/50'
                }`}
              >
                <Icon path={item.iconPath} />
                {item.name}
              </Link>
            );
          })}

          <div className="border-t border-indigo-800/50 my-2" />
          
          <Link
            href="/administracao"
            className="flex items-center gap-4 px-5 py-3.5 rounded-xl text-white text-base font-medium hover:bg-indigo-900/50 transition-colors"
          >
            <Icon path="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 0 0 2.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 0 0 1.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 0 0-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 0 0-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 0 0-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 0 0-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 0 0 1.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0z" />
            Administração
          </Link>
        </nav>
      </div>

      <div className="flex items-center gap-3">
        <div className="w-10 h-10 rounded-full border border-indigo-700/50 flex items-center justify-center text-white/50 font-bold text-lg">N</div>
        <Link
          href="/"
          onClick={() => localStorage.removeItem('cifa_auth')}
          className="flex-1 flex items-center gap-3 px-4 py-3 rounded-xl text-white text-base font-medium hover:bg-indigo-900/50 transition-colors"
        >
          <Icon path="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4 M16 17l5-5-5-5 M21 12H9" />
          Sair
        </Link>
      </div>
    </aside>
  );
}

// cifa-web/src/components/Sidebar.vue
<script setup lang="ts">
import { useRoute, useRouter } from 'vue-router'
import { 
  LayoutDashboard, 
  Users, 
  UserPlus, 
  FileText, 
  Settings, 
  LogOut 
} from 'lucide-vue-next'

const props = defineProps<{ isOpen: boolean }>()
const emit = defineEmits(['logout', 'close'])

const route = useRoute()
const router = useRouter()

const menuItems = [
  { name: 'Dashboard', path: '/admin/dashboard', icon: LayoutDashboard },
  { name: 'Estudantes', path: '/admin/estudantes', icon: Users },
  { name: 'Cadastro', path: '/admin/cadastro', icon: UserPlus },
  { name: 'Relatórios', path: '/admin/relatorios', icon: FileText },
]

const isActive = (path: string) => route.path === path

const navigate = (path: string) => {
  router.push(path)
  emit('close')
}
</script>

<template>
  <aside 
    :class="[
      'fixed left-0 top-0 h-[100dvh] w-64 bg-[#0A102E] text-white flex flex-col justify-between z-50 shadow-2xl transition-transform duration-300 ease-in-out lg:translate-x-0',
      isOpen ? 'translate-x-0' : '-translate-x-full'
    ]"
  >
    <div class="p-6 flex flex-col flex-1 overflow-y-auto custom-scrollbar">
      
      <div class="flex items-center gap-3 mb-10 select-none shrink-0">
        <h1 class="text-3xl font-bold tracking-wider">CIFA</h1>
        <div class="text-[0.6rem] leading-tight text-slate-300 font-medium uppercase tracking-tighter">
          <p>Controle Inteligente</p>
          <p>de Fluxo Acadêmico</p>
        </div>
      </div>

      <nav class="flex flex-col gap-2 shrink-0">
        <button 
          v-for="item in menuItems" 
          :key="item.path"
          @click="navigate(item.path)"
          :class="[
            'flex items-center gap-3 px-4 py-3 rounded-lg font-medium transition-all duration-200 text-left',
            isActive(item.path) ? 'bg-white text-[#0A102E] shadow-lg scale-[1.02]' : 'text-slate-300 hover:bg-white/10 hover:text-white'
          ]"
        >
          <component :is="item.icon" class="w-5 h-5 shrink-0" />
          <span class="truncate">{{ item.name }}</span>
        </button>
      </nav>

      <div class="w-full h-px bg-slate-700/50 my-6 shrink-0"></div>

      <button 
        @click="navigate('/admin/administracao')"
        :class="[
          'flex items-center gap-3 px-4 py-3 rounded-lg font-medium transition-all duration-200 text-left shrink-0',
          isActive('/admin/administracao') ? 'bg-white text-[#0A102E] shadow-lg scale-[1.02]' : 'text-slate-300 hover:bg-white/10 hover:text-white'
        ]"
      >
        <Settings class="w-5 h-5 shrink-0" />
        Gestão
      </button>
    </div>

    <div class="p-6 pt-4 mt-auto shrink-0 border-t border-slate-800/50 bg-[#0A102E]">
      <button 
        @click="emit('logout')"
        class="flex items-center gap-3 px-4 py-3 rounded-lg font-medium text-slate-400 hover:bg-red-500/10 hover:text-red-400 w-full transition-all duration-200 group text-left"
      >
        <LogOut class="w-5 h-5 shrink-0 transition-transform group-hover:-translate-x-1" />
        Sair do Sistema
      </button>
    </div>
  </aside>
</template>

<style scoped>
.custom-scrollbar::-webkit-scrollbar { width: 4px; }
.custom-scrollbar::-webkit-scrollbar-track { background: transparent; }
.custom-scrollbar::-webkit-scrollbar-thumb { background-color: #334155; border-radius: 10px; }
.custom-scrollbar:hover::-webkit-scrollbar-thumb { background-color: #475569; }
</style>
